module.exports = {
    baseUrl: 'https://opensource-demo.orangehrmlive.com/',
    loginHeader: 'Login',
    profileImgAlt: 'profile picture',
    mainHeader: 'PIM',
    mainUrl: 'viewEmployeeList',
    title: 'OrangeHRM',
    adminHeader: 'Admin',
    adminUrl: 'viewSystemUsers',
    jobHeader: 'Job Titles',
    jobUrl: 'viewJobTitleList',
    saveUrl: 'saveJobTitle',
    jobHeaderAdd: 'Add Job Title',
    jobHeaderEdit: 'Edit Job Title',
    jobTitle: 'Intern',
    descriptionPlaceholder: 'Type description here',
    jobDescription: 'Test cases creation',
    notePlaceholder: 'Add note',
    jobNote: 'Should perform test cases creation, maintenance and results reporting',
    saveBtnClass: 'orangehrm-left-space',
    errorMsg: 'Already exists',
    newJobTitle: 'Student',
    newJobDescription: 'Practice testing',
    success: 'Success'
}