module.exports = constants = {
    baseUrl: 'https://opensource-demo.orangehrmlive.com/',
    loginHeader: 'Login',
    login: 'Admin',
    pass: 'admin123',
    negativeLogin: ['admi', '123', 'Аdmin'],
    negativePass: ['admin123 ', '123admin', 'аdmin123'],
    profileImgAlt: "profile picture",
    mainHeader: "PIM",
    mainUrl: "viewEmployeeList",
    title: 'OrangeHRM',
    sideMenuText: ['Admin', 'PIM', 'Leave', 'Time', 'Recruitment', 'My Info', 'Performance', 'Dashboard', 'Directory', 'Maintenance', 'Buzz'],
    sideMenuElementsLength: 11,
    adminHeader: "Admin",
    adminUrl: "viewSystemUsers",
    topMenuText: ['User Management', 'Job', 'Organization', 'Qualifications', 'Nationalities', 'Corporate Branding', 'Configuration'],
    topMenuLength: 7,
    jobTitles: ['Job Titles', 'Pay Grades', 'Employment Status', 'Job Categories', 'Work Shifts'],
    jobTitlesLength: 5,
    jobHeader: "Job Titles",
    jobUrl: "viewJobTitleList",
    saveUrl: "saveJobTitle",
    jobHeaderAdd: "Add Job Title",
    jobHeaderEdit: "Edit Job Title",
    jobTitle: "Intern",
    descriptionPlaceholder: "Type description here",
    jobDescription: "Test cases creation",
    notePlaceholder: "Add note",
    jobNote: "Should perform test cases creation, maintenance and results reporting",
    saveBtnClass: "orangehrm-left-space",
    errorMsg: "Already exists",
    newJobTitle: "Student",
    newJobDescription: "Practice testing",
    logoutMenuLength: 4,
    logoutMenuText: ['About', 'Support', 'Change Password', 'Logout'],
}