name: Orangehrmlive e2e test and negative login test with Chrome browser

on: [push]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm install
      - name: WDIO run
        run: npm run run:github
      - name: Output test results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: allure-report
          retention-days: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report